import { PHASE1_SKILLS, PHASE1_TOPIC_LABELS } from "./skill-map";
import type { Phase1ModuleDefinition, Phase1ProgramDefinition } from "./types";

export const PHASE1_MODULES: Phase1ModuleDefinition[] = [
  {
    moduleKey: "phase1-document-workflow",
    phaseKey: "phase1",
    titleZh: "模組 1：文件流程與正式書面語",
    titleEn: "Module 1: Document workflow and formal register",
    summaryZh: "從文件、交件、審閱與商務信件語氣切入，先建立最常用的工作情境字彙與閱讀基礎。",
    summaryEn: "Starts with document workflow, review actions, and business email tone to build the safest high-frequency foundation first.",
    targetSkills: [
      "vocabulary.document-workflow",
      "vocabulary.formal-register",
      "reading.detail-retrieval",
      "reading.purpose-and-intent",
    ],
    entryCriteria: {
      recommendedWhenWeakSkillsAnyOf: [
        "vocabulary.document-workflow",
        "vocabulary.formal-register",
        "reading.detail-retrieval",
      ],
      suggestedIfDiagnosticAccuracyBelow: 75,
      suggestedIfCheckpointAccuracyBelow: 80,
    },
    lessonObjectives: [
      { zh: "辨認交件、審閱、起草、彙報等常見工作動作字彙", en: "Recognize core workflow actions such as submit, review, draft, and report." },
      { zh: "理解正式書面語與一般口語在選項上的差別", en: "Distinguish formal written English from merely conversational wording." },
      { zh: "練習從 email / memo 細節定位答案", en: "Locate answers from specific email or memo details." },
    ],
    lessonOutline: [
      { zh: "Lesson A：文件處理動作與片語動詞", en: "Lesson A: Document actions and phrasal verbs" },
      { zh: "Lesson B：正式書面搭配與常見公告語氣", en: "Lesson B: Formal register and announcement tone" },
      { zh: "Lesson C：email / memo 細節與目的判讀", en: "Lesson C: Email / memo detail and purpose reading" },
    ],
    drillBlueprint: {
      mode: "lesson_drill",
      questionCount: 8,
      skills: [
        "vocabulary.document-workflow",
        "vocabulary.formal-register",
        "reading.detail-retrieval",
      ],
      recommendedDifficultyMix: { A: 0.5, B: 0.5 },
      allowHints: true,
      note: "Front-load approachable office and communication items so the learner can build confidence while still seeing business-style language.",
    },
    checkpointBlueprint: {
      mode: "checkpoint",
      questionCount: 10,
      skills: [
        "vocabulary.document-workflow",
        "vocabulary.formal-register",
        "reading.detail-retrieval",
        "reading.purpose-and-intent",
      ],
      recommendedDifficultyMix: { A: 0.4, B: 0.5, C: 0.1 },
      allowHints: false,
      note: "Checkpoint mixes vocabulary recognition with short-document reading so success means the learner can use the vocabulary in context.",
    },
    checkpointRule: {
      passAccuracyPercent: 75,
      questionCount: 10,
      allowHintBeforeSubmit: false,
    },
    recommendedDrillCount: 2,
    recommendedReviewWindowDays: 3,
    listeningReady: false,
  },
  {
    moduleKey: "phase1-core-grammar-control",
    phaseKey: "phase1",
    titleZh: "模組 2：核心文法控制",
    titleEn: "Module 2: Core grammar control",
    summaryZh: "用最影響 Part 5 命中率的動詞控制與句型搭配，建立可持續的文法解題步驟。",
    summaryEn: "Builds a sustainable Part 5 solving process around verb control and pattern control, the most common grammar bottlenecks.",
    targetSkills: ["grammar.verb-control", "grammar.pattern-control"],
    entryCriteria: {
      recommendedWhenWeakSkillsAnyOf: ["grammar.verb-control", "grammar.pattern-control"],
      suggestedIfDiagnosticAccuracyBelow: 70,
      suggestedIfCheckpointAccuracyBelow: 78,
    },
    lessonObjectives: [
      { zh: "先看時態 / 語態 / 主詞再看語意", en: "Check tense, voice, and subject clues before reading for meaning." },
      { zh: "辨認常見動詞搭配與介系詞框架", en: "Recognize common verb patterns and preposition frames." },
      { zh: "把文法題拆成固定檢查順序", en: "Turn grammar items into a repeatable inspection sequence." },
    ],
    lessonOutline: [
      { zh: "Lesson A：時態、被動、主詞動詞一致", en: "Lesson A: Tense, passive voice, subject-verb agreement" },
      { zh: "Lesson B：動名詞 / 不定詞與介系詞搭配", en: "Lesson B: Gerund / infinitive and preposition patterns" },
      { zh: "Lesson C：錯題回放與規則摘要", en: "Lesson C: Error replay and rule recap" },
    ],
    drillBlueprint: {
      mode: "lesson_drill",
      questionCount: 10,
      skills: ["grammar.verb-control", "grammar.pattern-control"],
      recommendedDifficultyMix: { A: 0.4, B: 0.5, C: 0.1 },
      allowHints: true,
      note: "Drill should stay focused and hint-first so the learner learns the rule before the system converts mistakes into spaced review.",
    },
    checkpointBlueprint: {
      mode: "checkpoint",
      questionCount: 12,
      skills: ["grammar.verb-control", "grammar.pattern-control"],
      recommendedDifficultyMix: { A: 0.3, B: 0.5, C: 0.2 },
      allowHints: false,
      note: "Checkpoint should test whether the learner can apply grammar rules without scaffolding in a TOEIC-like selection flow.",
    },
    checkpointRule: {
      passAccuracyPercent: 78,
      questionCount: 12,
      allowHintBeforeSubmit: false,
      remediationModuleOnFail: "phase1-document-workflow",
    },
    recommendedDrillCount: 3,
    recommendedReviewWindowDays: 2,
    listeningReady: false,
  },
  {
    moduleKey: "phase1-notices-and-decisions",
    phaseKey: "phase1",
    titleZh: "模組 3：公告、判斷與決策",
    titleEn: "Module 3: Notices, judgment, and decisions",
    summaryZh: "把 sentence linking 文法同目的 / 意圖 / 推論閱讀整合，訓練較接近真實考場的判斷能力。",
    summaryEn: "Combines sentence-linking grammar with purpose, intent, and inference reading for more authentic decision-making practice.",
    targetSkills: [
      "grammar.sentence-linking",
      "reading.purpose-and-intent",
      "reading.inference-and-process-logic",
    ],
    entryCriteria: {
      recommendedWhenWeakSkillsAnyOf: [
        "grammar.sentence-linking",
        "reading.purpose-and-intent",
        "reading.inference-and-process-logic",
      ],
      suggestedIfDiagnosticAccuracyBelow: 72,
      suggestedIfCheckpointAccuracyBelow: 80,
    },
    lessonObjectives: [
      { zh: "看懂長句中連接詞與修飾的邏輯關係", en: "Decode conjunctions and modifiers in longer sentences." },
      { zh: "從語氣與目的推斷寫信者要做什麼", en: "Infer what the writer wants based on tone and purpose." },
      { zh: "把流程與結果推論變成有步驟的閱讀行為", en: "Turn process and outcome inference into a step-by-step reading method." },
    ],
    lessonOutline: [
      { zh: "Lesson A：連接詞、關係子句與分詞修飾", en: "Lesson A: Conjunctions, relative clauses, and participles" },
      { zh: "Lesson B：公告目的、意圖與流程推論", en: "Lesson B: Notice purpose, intent, and process inference" },
      { zh: "Lesson C：checkpoint 前的混合判斷練習", en: "Lesson C: Mixed judgment practice before checkpoint" },
    ],
    drillBlueprint: {
      mode: "lesson_drill",
      questionCount: 8,
      skills: [
        "grammar.sentence-linking",
        "reading.purpose-and-intent",
        "reading.inference-and-process-logic",
      ],
      recommendedDifficultyMix: { B: 0.7, C: 0.3 },
      allowHints: true,
      note: "Hints should progressively narrow the evidence span rather than reveal the answer, so the learner still does the reasoning work.",
    },
    checkpointBlueprint: {
      mode: "checkpoint",
      questionCount: 10,
      skills: [
        "grammar.sentence-linking",
        "reading.purpose-and-intent",
        "reading.inference-and-process-logic",
      ],
      recommendedDifficultyMix: { A: 0.1, B: 0.5, C: 0.4 },
      allowHints: false,
      note: "Checkpoint should feel noticeably more test-like than drill mode and reward evidence-based reasoning over clue spotting.",
    },
    checkpointRule: {
      passAccuracyPercent: 80,
      questionCount: 10,
      allowHintBeforeSubmit: false,
      remediationModuleOnFail: "phase1-core-grammar-control",
    },
    recommendedDrillCount: 2,
    recommendedReviewWindowDays: 3,
    listeningReady: true,
  },
  {
    moduleKey: "phase1-business-process-reading",
    phaseKey: "phase1",
    titleZh: "模組 4：跨部門流程閱讀",
    titleEn: "Module 4: Cross-functional process reading",
    summaryZh: "聚焦 HR、finance、logistics、tech 等多部門情境，讓 vocab、reading、inference 在更廣題材中整合。",
    summaryEn: "Expands into HR, finance, logistics, and technology so vocabulary and reading inference transfer across broader business topics.",
    targetSkills: [
      "vocabulary.domain-and-abstract-meaning",
      "reading.detail-retrieval",
      "reading.inference-and-process-logic",
      "reading.contextual-meaning",
    ],
    entryCriteria: {
      recommendedWhenWeakSkillsAnyOf: [
        "vocabulary.domain-and-abstract-meaning",
        "reading.contextual-meaning",
      ],
      suggestedIfDiagnosticAccuracyBelow: 74,
      suggestedIfCheckpointAccuracyBelow: 82,
    },
    lessonObjectives: [
      { zh: "把陌生題材拆成可理解的部門情境", en: "Break unfamiliar topics into recognizable business contexts." },
      { zh: "從上下文推斷字義而不是只靠背誦", en: "Infer meaning from context rather than memorized definitions alone." },
      { zh: "在跨部門流程中抓重點與推論結果", en: "Track details and outcomes in cross-functional process passages." },
    ],
    lessonOutline: [
      { zh: "Lesson A：財務、物流、科技情境字彙", en: "Lesson A: Finance, logistics, and technology vocabulary in context" },
      { zh: "Lesson B：流程閱讀與語境字義", en: "Lesson B: Process reading and meaning in context" },
      { zh: "Lesson C：跨主題混合 drill", en: "Lesson C: Cross-topic mixed drill" },
    ],
    drillBlueprint: {
      mode: "mixed_practice",
      questionCount: 10,
      skills: [
        "vocabulary.domain-and-abstract-meaning",
        "reading.detail-retrieval",
        "reading.contextual-meaning",
      ],
      recommendedDifficultyMix: { A: 0.2, B: 0.5, C: 0.3 },
      allowHints: true,
      note: "This module is the bridge between focused learning and full mixed practice, so drill mode can start to resemble a guided exam block.",
    },
    checkpointBlueprint: {
      mode: "checkpoint",
      questionCount: 12,
      skills: [
        "vocabulary.domain-and-abstract-meaning",
        "reading.detail-retrieval",
        "reading.inference-and-process-logic",
        "reading.contextual-meaning",
      ],
      recommendedDifficultyMix: { A: 0.2, B: 0.5, C: 0.3 },
      allowHints: false,
      note: "Checkpoint verifies that the learner can transfer earlier skills into less familiar subject matter.",
    },
    checkpointRule: {
      passAccuracyPercent: 82,
      questionCount: 12,
      allowHintBeforeSubmit: false,
      remediationModuleOnFail: "phase1-notices-and-decisions",
    },
    recommendedDrillCount: 2,
    recommendedReviewWindowDays: 4,
    listeningReady: true,
  },
  {
    moduleKey: "phase1-cross-topic-checkpoint",
    phaseKey: "phase1",
    titleZh: "模組 5：Phase 1 綜合檢核",
    titleEn: "Module 5: Phase 1 integrated checkpoint",
    summaryZh: "整合前四個模組的 vocab、grammar、reading 技能，用於判斷是否完成 Phase 1。",
    summaryEn: "Combines the first four modules into a final integrated checkpoint that decides whether Phase 1 is complete.",
    targetSkills: [
      "vocabulary.document-workflow",
      "vocabulary.formal-register",
      "vocabulary.domain-and-abstract-meaning",
      "grammar.verb-control",
      "grammar.pattern-control",
      "grammar.sentence-linking",
      "reading.detail-retrieval",
      "reading.purpose-and-intent",
      "reading.inference-and-process-logic",
      "reading.contextual-meaning",
    ],
    entryCriteria: {
      recommendedWhenWeakSkillsAnyOf: ["reading.inference-and-process-logic"],
      suggestedIfDiagnosticAccuracyBelow: 80,
      suggestedIfCheckpointAccuracyBelow: 85,
    },
    lessonObjectives: [
      { zh: "以綜合任務檢驗前面所有技能是否能一起運作", en: "Validate whether all previous skills can operate together in one integrated task set." },
      { zh: "找出仍需回補的單一技能或題型", en: "Identify the last remaining skill or item-type gaps before moving on." },
    ],
    lessonOutline: [
      { zh: "Lesson A：Phase 1 review checklist", en: "Lesson A: Phase 1 review checklist" },
      { zh: "Lesson B：錯題群組回看", en: "Lesson B: Error cluster review" },
    ],
    drillBlueprint: {
      mode: "review",
      questionCount: 10,
      skills: [
        "grammar.verb-control",
        "reading.detail-retrieval",
        "reading.inference-and-process-logic",
      ],
      recommendedDifficultyMix: { A: 0.2, B: 0.5, C: 0.3 },
      allowHints: true,
      note: "The final review block should recycle the learner's weakest Phase 1 clusters before the integrated checkpoint.",
    },
    checkpointBlueprint: {
      mode: "checkpoint",
      questionCount: 15,
      skills: [
        "vocabulary.document-workflow",
        "vocabulary.formal-register",
        "vocabulary.domain-and-abstract-meaning",
        "grammar.verb-control",
        "grammar.pattern-control",
        "grammar.sentence-linking",
        "reading.detail-retrieval",
        "reading.purpose-and-intent",
        "reading.inference-and-process-logic",
        "reading.contextual-meaning",
      ],
      recommendedDifficultyMix: { A: 0.2, B: 0.5, C: 0.3 },
      allowHints: false,
      note: "Integrated checkpoint is the first place where the learner should feel a controlled exam-like blend across all three categories.",
    },
    checkpointRule: {
      passAccuracyPercent: 85,
      questionCount: 15,
      allowHintBeforeSubmit: false,
      remediationModuleOnFail: "phase1-business-process-reading",
    },
    recommendedDrillCount: 1,
    recommendedReviewWindowDays: 5,
    listeningReady: true,
  },
];

export const PHASE1_MVP_MODULE_KEYS = [
  "phase1-document-workflow",
  "phase1-core-grammar-control",
  "phase1-notices-and-decisions",
] as const;

export const PHASE1_PROGRAM: Phase1ProgramDefinition = {
  programKey: "phase1",
  titleZh: "Phase 1 閉環學習計畫",
  titleEn: "Phase 1 closed-loop learning program",
  summaryZh: "以閱讀 / 文法 / 字彙為主，透過診斷、lesson、drill、checkpoint、review 組成第一階段完整學習閉環。",
  summaryEn: "A Reading / Grammar / Vocabulary-first learning program built around diagnostic, lesson, drill, checkpoint, and review loops.",
  topics: PHASE1_TOPIC_LABELS,
  skills: PHASE1_SKILLS,
  modules: PHASE1_MODULES,
  mvpModuleKeys: [...PHASE1_MVP_MODULE_KEYS],
};
