/**
 * LearningSkill seed — 58 fine-grained skill / vocab / strategy points used by the
 * 30-day closed-loop StudyPlan sequencing.
 *
 * These rows are *orthogonal* to LearningTopic (12 Phase1 business scenarios).
 * A single QuestionBankItem belongs to (at most) one Phase1 topic *and* one
 * primary LearningSkill.
 *
 * Composition (matches 2026-04 final plan §5):
 *   - Grammar      22 rows
 *   - Vocabulary   18 rows
 *   - Phrase       10 rows
 *   - Strategy      8 rows
 *   TOTAL          58 rows
 *
 * `parentSkillKey` loosely maps to the coarse Phase1SkillDefinition.skillKey
 * constants in src/content/programs/phase1/skill-map.ts. It is stored as a
 * free-form string (not a FK) because that taxonomy lives in content files.
 */

export type LearningSkillSeed = {
  skillCode: string;
  category: "grammar" | "vocabulary" | "phrase" | "strategy";
  subCategory: string | null;
  labelZh: string;
  labelEn: string;
  priority: "P1" | "P2" | "P3" | "P4";
  difficultyBand: "beginner" | "intermediate" | "advanced";
  toeicScoreBand: "400-550" | "500-700" | "700-850" | "850+";
  part5Frequency: number;
  part6Frequency: number;
  part7Frequency: number;
  parentSkillKey: string | null;
  recommendedWeek: number | null;
  within30DayPlan: boolean;
  learnPrereqJson: string[] | null;
  learnUnlocksJson: string[] | null;
  orderIndex: number;
};

// ─────────────────────────────────────────────
//  GRAMMAR (22 rows)
// ─────────────────────────────────────────────
const GRAMMAR_SKILLS: LearningSkillSeed[] = [
  {
    skillCode: "grammar_svc",
    category: "grammar",
    subCategory: "sentence_pattern",
    labelZh: "SVC 句型",
    labelEn: "Subject-Verb-Complement pattern",
    priority: "P1",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 4,
    part6Frequency: 3,
    part7Frequency: 2,
    parentSkillKey: "grammar.pattern-control",
    recommendedWeek: 1,
    within30DayPlan: true,
    learnPrereqJson: null,
    learnUnlocksJson: ["grammar_svoc"],
    orderIndex: 100,
  },
  {
    skillCode: "grammar_svoo",
    category: "grammar",
    subCategory: "sentence_pattern",
    labelZh: "SVOO 授與動詞",
    labelEn: "Ditransitive (SVOO) pattern",
    priority: "P1",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 3,
    part6Frequency: 3,
    part7Frequency: 2,
    parentSkillKey: "grammar.pattern-control",
    recommendedWeek: 1,
    within30DayPlan: true,
    learnPrereqJson: ["grammar_svc"],
    learnUnlocksJson: ["grammar_svoc"],
    orderIndex: 101,
  },
  {
    skillCode: "grammar_svoc",
    category: "grammar",
    subCategory: "sentence_pattern",
    labelZh: "SVOC 句型",
    labelEn: "Object-complement (SVOC) pattern",
    priority: "P1",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 3,
    part6Frequency: 2,
    part7Frequency: 2,
    parentSkillKey: "grammar.pattern-control",
    // Day 27 情境 A (Mini mock 60%+) 可選學 — so technically not guaranteed in 30 days
    recommendedWeek: 4,
    within30DayPlan: false,
    learnPrereqJson: ["grammar_svc", "grammar_svoo"],
    learnUnlocksJson: null,
    orderIndex: 102,
  },
  {
    skillCode: "grammar_gerund",
    category: "grammar",
    subCategory: "verbal_form",
    labelZh: "Gerund 動名詞",
    labelEn: "Gerunds (V-ing as noun)",
    priority: "P1",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 4,
    part6Frequency: 3,
    part7Frequency: 3,
    parentSkillKey: "grammar.pattern-control",
    recommendedWeek: 2,
    within30DayPlan: true,
    learnPrereqJson: null,
    learnUnlocksJson: ["grammar_infinitive"],
    orderIndex: 110,
  },
  {
    skillCode: "grammar_participle",
    category: "grammar",
    subCategory: "verbal_form",
    labelZh: "Participle 分詞",
    labelEn: "Participles (-ed / -ing as modifier)",
    priority: "P1",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 4,
    part6Frequency: 4,
    part7Frequency: 3,
    parentSkillKey: "grammar.sentence-linking",
    recommendedWeek: 2,
    within30DayPlan: true,
    learnPrereqJson: null,
    learnUnlocksJson: ["grammar_adj_clause"],
    orderIndex: 111,
  },
  {
    skillCode: "grammar_infinitive",
    category: "grammar",
    subCategory: "verbal_form",
    labelZh: "Infinitive 不定詞",
    labelEn: "Infinitives (to + V)",
    priority: "P2",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 4,
    part6Frequency: 3,
    part7Frequency: 2,
    parentSkillKey: "grammar.pattern-control",
    recommendedWeek: null,
    within30DayPlan: false,
    learnPrereqJson: ["grammar_gerund"],
    learnUnlocksJson: null,
    orderIndex: 112,
  },
  {
    skillCode: "grammar_noun_clause",
    category: "grammar",
    subCategory: "clause",
    labelZh: "Noun Clause 名詞子句",
    labelEn: "Noun clause (that / whether / what)",
    priority: "P1",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 3,
    part6Frequency: 3,
    part7Frequency: 3,
    parentSkillKey: "grammar.sentence-linking",
    recommendedWeek: 3,
    within30DayPlan: true,
    learnPrereqJson: null,
    learnUnlocksJson: ["grammar_adj_clause", "grammar_adv_clause"],
    orderIndex: 120,
  },
  {
    skillCode: "grammar_adj_clause",
    category: "grammar",
    subCategory: "clause",
    labelZh: "形容詞子句",
    labelEn: "Adjective clause (who / which / that)",
    priority: "P2",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 3,
    part6Frequency: 3,
    part7Frequency: 3,
    parentSkillKey: "grammar.sentence-linking",
    recommendedWeek: null,
    within30DayPlan: false,
    learnPrereqJson: ["grammar_noun_clause"],
    learnUnlocksJson: ["grammar_relative_pron"],
    orderIndex: 121,
  },
  {
    skillCode: "grammar_adv_clause",
    category: "grammar",
    subCategory: "clause",
    labelZh: "副詞子句",
    labelEn: "Adverb clause (when / while / because / so that)",
    priority: "P2",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 3,
    part6Frequency: 3,
    part7Frequency: 2,
    parentSkillKey: "grammar.sentence-linking",
    recommendedWeek: null,
    within30DayPlan: false,
    learnPrereqJson: ["grammar_noun_clause"],
    learnUnlocksJson: null,
    orderIndex: 122,
  },
  {
    skillCode: "grammar_relative_pron",
    category: "grammar",
    subCategory: "clause",
    labelZh: "關係代名詞",
    labelEn: "Relative pronoun selection",
    priority: "P2",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 3,
    part6Frequency: 2,
    part7Frequency: 2,
    parentSkillKey: "grammar.sentence-linking",
    recommendedWeek: null,
    within30DayPlan: false,
    learnPrereqJson: ["grammar_adj_clause"],
    learnUnlocksJson: null,
    orderIndex: 123,
  },
  {
    skillCode: "grammar_past_perfect",
    category: "grammar",
    subCategory: "tense",
    labelZh: "過去完成式",
    labelEn: "Past Perfect tense",
    priority: "P2",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 3,
    part6Frequency: 3,
    part7Frequency: 2,
    parentSkillKey: "grammar.verb-control",
    recommendedWeek: 3,
    within30DayPlan: true,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 130,
  },
  {
    skillCode: "grammar_present_perfect",
    category: "grammar",
    subCategory: "tense",
    labelZh: "現在完成式",
    labelEn: "Present Perfect tense",
    priority: "P3",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 3,
    part6Frequency: 3,
    part7Frequency: 2,
    parentSkillKey: "grammar.verb-control",
    recommendedWeek: 4,
    within30DayPlan: true,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 131,
  },
  {
    skillCode: "grammar_nouns_count",
    category: "grammar",
    subCategory: "noun_related",
    labelZh: "可數 / 不可數名詞",
    labelEn: "Countable / uncountable nouns",
    priority: "P2",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 3,
    part6Frequency: 2,
    part7Frequency: 1,
    parentSkillKey: "grammar.pattern-control",
    recommendedWeek: 3,
    within30DayPlan: true,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 140,
  },
  {
    skillCode: "grammar_preposition",
    category: "grammar",
    subCategory: "collocation",
    labelZh: "介詞搭配",
    labelEn: "Preposition collocations",
    priority: "P2",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 4,
    part6Frequency: 3,
    part7Frequency: 2,
    parentSkillKey: "grammar.pattern-control",
    recommendedWeek: 4,
    within30DayPlan: true,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 150,
  },
  {
    skillCode: "grammar_conjunction",
    category: "grammar",
    subCategory: "linking",
    labelZh: "連接詞邏輯",
    labelEn: "Conjunction & logic",
    priority: "P2",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 4,
    part6Frequency: 3,
    part7Frequency: 3,
    parentSkillKey: "grammar.sentence-linking",
    recommendedWeek: 4,
    within30DayPlan: true,
    learnPrereqJson: null,
    learnUnlocksJson: ["grammar_paired_conj"],
    orderIndex: 151,
  },
  {
    skillCode: "grammar_paired_conj",
    category: "grammar",
    subCategory: "linking",
    labelZh: "成對連接詞",
    labelEn: "Paired conjunctions (not only / both / either)",
    priority: "P3",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 2,
    part6Frequency: 2,
    part7Frequency: 2,
    parentSkillKey: "grammar.sentence-linking",
    recommendedWeek: null,
    within30DayPlan: false,
    learnPrereqJson: ["grammar_conjunction"],
    learnUnlocksJson: null,
    orderIndex: 152,
  },
  {
    skillCode: "grammar_adjective",
    category: "grammar",
    subCategory: "adj_adv",
    labelZh: "形容詞用法",
    labelEn: "Adjective usage",
    priority: "P3",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 3,
    part6Frequency: 2,
    part7Frequency: 1,
    parentSkillKey: "grammar.pattern-control",
    recommendedWeek: null,
    within30DayPlan: false,
    learnPrereqJson: null,
    learnUnlocksJson: ["grammar_comparative"],
    orderIndex: 160,
  },
  {
    skillCode: "grammar_comparative",
    category: "grammar",
    subCategory: "adj_adv",
    labelZh: "比較級與最高級",
    labelEn: "Comparatives & superlatives",
    priority: "P3",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 2,
    part6Frequency: 2,
    part7Frequency: 1,
    parentSkillKey: "grammar.pattern-control",
    recommendedWeek: null,
    within30DayPlan: false,
    learnPrereqJson: ["grammar_adjective"],
    learnUnlocksJson: null,
    orderIndex: 161,
  },
  {
    skillCode: "grammar_passive",
    category: "grammar",
    subCategory: "voice",
    labelZh: "被動語態進階",
    labelEn: "Advanced passive voice",
    priority: "P3",
    difficultyBand: "advanced",
    toeicScoreBand: "700-850",
    part5Frequency: 3,
    part6Frequency: 2,
    part7Frequency: 2,
    parentSkillKey: "grammar.verb-control",
    recommendedWeek: null,
    within30DayPlan: false,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 170,
  },
  {
    skillCode: "grammar_subjunctive",
    category: "grammar",
    subCategory: "mood",
    labelZh: "假設語氣",
    labelEn: "Subjunctive / if-clauses",
    priority: "P4",
    difficultyBand: "advanced",
    toeicScoreBand: "700-850",
    part5Frequency: 2,
    part6Frequency: 2,
    part7Frequency: 2,
    parentSkillKey: "grammar.verb-control",
    recommendedWeek: null,
    within30DayPlan: false,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 171,
  },
  {
    skillCode: "grammar_inversion",
    category: "grammar",
    subCategory: "advanced",
    labelZh: "倒裝句",
    labelEn: "Inversion (Not only... but)",
    priority: "P4",
    difficultyBand: "advanced",
    toeicScoreBand: "850+",
    part5Frequency: 1,
    part6Frequency: 1,
    part7Frequency: 1,
    parentSkillKey: "grammar.sentence-linking",
    recommendedWeek: null,
    within30DayPlan: false,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 180,
  },
  {
    skillCode: "grammar_emphatic",
    category: "grammar",
    subCategory: "advanced",
    labelZh: "強調句",
    labelEn: "Emphatic / cleft (It is... that)",
    priority: "P4",
    difficultyBand: "advanced",
    toeicScoreBand: "850+",
    part5Frequency: 1,
    part6Frequency: 1,
    part7Frequency: 1,
    parentSkillKey: "grammar.sentence-linking",
    recommendedWeek: null,
    within30DayPlan: false,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 181,
  },
];

// ─────────────────────────────────────────────
//  VOCABULARY (18 rows)
// ─────────────────────────────────────────────
const VOCABULARY_SKILLS: LearningSkillSeed[] = [
  {
    skillCode: "vocab_medical",
    category: "vocabulary",
    subCategory: "workplace_domain",
    labelZh: "醫療與健康",
    labelEn: "Medical & health vocabulary",
    priority: "P1",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 3,
    part6Frequency: 3,
    part7Frequency: 4,
    parentSkillKey: "vocabulary.domain-and-abstract-meaning",
    recommendedWeek: 1,
    within30DayPlan: true,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 200,
  },
  {
    skillCode: "vocab_daily_life",
    category: "vocabulary",
    subCategory: "daily",
    labelZh: "日常生活",
    labelEn: "Daily life vocabulary",
    priority: "P1",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 3,
    part6Frequency: 3,
    part7Frequency: 4,
    parentSkillKey: "vocabulary.domain-and-abstract-meaning",
    recommendedWeek: 2,
    within30DayPlan: true,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 201,
  },
  {
    skillCode: "vocab_environment",
    category: "vocabulary",
    subCategory: "workplace_domain",
    labelZh: "環境與生態",
    labelEn: "Environment & ecology vocabulary",
    priority: "P1",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 2,
    part6Frequency: 2,
    part7Frequency: 3,
    parentSkillKey: "vocabulary.domain-and-abstract-meaning",
    recommendedWeek: 3,
    within30DayPlan: true,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 202,
  },
  {
    skillCode: "vocab_communication",
    category: "vocabulary",
    subCategory: "abstract",
    labelZh: "抽象溝通",
    labelEn: "Abstract communication vocabulary",
    priority: "P1",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 3,
    part6Frequency: 3,
    part7Frequency: 4,
    parentSkillKey: "vocabulary.formal-register",
    recommendedWeek: 3,
    within30DayPlan: true,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 203,
  },
  {
    skillCode: "vocab_false_friends",
    category: "vocabulary",
    subCategory: "confusable",
    labelZh: "易混淆詞",
    labelEn: "False friends / confusable pairs",
    priority: "P1",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 4,
    part6Frequency: 3,
    part7Frequency: 3,
    parentSkillKey: "vocabulary.formal-register",
    recommendedWeek: 1,
    within30DayPlan: true,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 204,
  },
  {
    skillCode: "vocab_office_general",
    category: "vocabulary",
    subCategory: "workplace_domain",
    labelZh: "辦公室通用",
    labelEn: "Office general vocabulary",
    priority: "P2",
    difficultyBand: "beginner",
    toeicScoreBand: "400-550",
    part5Frequency: 5,
    part6Frequency: 4,
    part7Frequency: 4,
    parentSkillKey: "vocabulary.document-workflow",
    recommendedWeek: null,
    within30DayPlan: false,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 210,
  },
  {
    skillCode: "vocab_meetings",
    category: "vocabulary",
    subCategory: "workplace_domain",
    labelZh: "會議與報告",
    labelEn: "Meetings & reporting vocabulary",
    priority: "P2",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 4,
    part6Frequency: 4,
    part7Frequency: 3,
    parentSkillKey: "vocabulary.formal-register",
    recommendedWeek: null,
    within30DayPlan: false,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 211,
  },
  {
    skillCode: "vocab_hr_recruitment",
    category: "vocabulary",
    subCategory: "workplace_domain",
    labelZh: "人事招聘",
    labelEn: "HR & recruitment vocabulary",
    priority: "P2",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 3,
    part6Frequency: 3,
    part7Frequency: 4,
    parentSkillKey: "vocabulary.formal-register",
    recommendedWeek: null,
    within30DayPlan: false,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 212,
  },
  {
    skillCode: "vocab_marketing_sales",
    category: "vocabulary",
    subCategory: "workplace_domain",
    labelZh: "行銷業務",
    labelEn: "Marketing & sales vocabulary",
    priority: "P2",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 3,
    part6Frequency: 3,
    part7Frequency: 4,
    parentSkillKey: "vocabulary.formal-register",
    recommendedWeek: null,
    within30DayPlan: false,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 213,
  },
  {
    skillCode: "vocab_finance_banking",
    category: "vocabulary",
    subCategory: "workplace_domain",
    labelZh: "財務與銀行",
    labelEn: "Finance & banking vocabulary",
    priority: "P2",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 3,
    part6Frequency: 3,
    part7Frequency: 4,
    parentSkillKey: "vocabulary.domain-and-abstract-meaning",
    recommendedWeek: null,
    within30DayPlan: false,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 214,
  },
  {
    skillCode: "vocab_logistics",
    category: "vocabulary",
    subCategory: "workplace_domain",
    labelZh: "物流運輸",
    labelEn: "Logistics & transport vocabulary",
    priority: "P2",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 3,
    part6Frequency: 3,
    part7Frequency: 3,
    parentSkillKey: "vocabulary.domain-and-abstract-meaning",
    recommendedWeek: null,
    within30DayPlan: false,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 215,
  },
  {
    skillCode: "vocab_technology",
    category: "vocabulary",
    subCategory: "workplace_domain",
    labelZh: "科技與 IT",
    labelEn: "Technology & IT vocabulary",
    priority: "P2",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 3,
    part6Frequency: 3,
    part7Frequency: 4,
    parentSkillKey: "vocabulary.domain-and-abstract-meaning",
    recommendedWeek: null,
    within30DayPlan: false,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 216,
  },
  {
    skillCode: "vocab_travel",
    category: "vocabulary",
    subCategory: "daily",
    labelZh: "出差與交通",
    labelEn: "Travel & transportation vocabulary",
    priority: "P2",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 3,
    part6Frequency: 3,
    part7Frequency: 4,
    parentSkillKey: "vocabulary.domain-and-abstract-meaning",
    recommendedWeek: null,
    within30DayPlan: false,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 220,
  },
  {
    skillCode: "vocab_contracts",
    category: "vocabulary",
    subCategory: "workplace_domain",
    labelZh: "合約與法律",
    labelEn: "Contracts & legal vocabulary",
    priority: "P3",
    difficultyBand: "advanced",
    toeicScoreBand: "700-850",
    part5Frequency: 3,
    part6Frequency: 3,
    part7Frequency: 4,
    parentSkillKey: "vocabulary.formal-register",
    recommendedWeek: null,
    within30DayPlan: false,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 230,
  },
  {
    skillCode: "vocab_events",
    category: "vocabulary",
    subCategory: "workplace_domain",
    labelZh: "活動籌辦",
    labelEn: "Events vocabulary",
    priority: "P3",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 2,
    part6Frequency: 3,
    part7Frequency: 3,
    parentSkillKey: "vocabulary.formal-register",
    recommendedWeek: null,
    within30DayPlan: false,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 231,
  },
  {
    skillCode: "vocab_hotel_dining",
    category: "vocabulary",
    subCategory: "daily",
    labelZh: "酒店與餐飲",
    labelEn: "Hotel & dining vocabulary",
    priority: "P3",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 2,
    part6Frequency: 3,
    part7Frequency: 4,
    parentSkillKey: "vocabulary.domain-and-abstract-meaning",
    recommendedWeek: null,
    within30DayPlan: false,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 232,
  },
  {
    skillCode: "vocab_construction",
    category: "vocabulary",
    subCategory: "workplace_domain",
    labelZh: "建築施工",
    labelEn: "Construction vocabulary",
    priority: "P4",
    difficultyBand: "advanced",
    toeicScoreBand: "700-850",
    part5Frequency: 1,
    part6Frequency: 2,
    part7Frequency: 2,
    parentSkillKey: "vocabulary.domain-and-abstract-meaning",
    recommendedWeek: null,
    within30DayPlan: false,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 240,
  },
  {
    skillCode: "vocab_real_estate",
    category: "vocabulary",
    subCategory: "workplace_domain",
    labelZh: "房地產",
    labelEn: "Real estate vocabulary",
    priority: "P4",
    difficultyBand: "advanced",
    toeicScoreBand: "700-850",
    part5Frequency: 1,
    part6Frequency: 2,
    part7Frequency: 2,
    parentSkillKey: "vocabulary.domain-and-abstract-meaning",
    recommendedWeek: null,
    within30DayPlan: false,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 241,
  },
];

// ─────────────────────────────────────────────
//  PHRASE (10 rows)
// ─────────────────────────────────────────────
const PHRASE_SKILLS: LearningSkillSeed[] = [
  {
    skillCode: "phrase_documents",
    category: "phrase",
    subCategory: "workplace",
    labelZh: "文書作業片語",
    labelEn: "Document-workflow phrases",
    priority: "P1",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 3,
    part6Frequency: 4,
    part7Frequency: 3,
    parentSkillKey: "vocabulary.document-workflow",
    recommendedWeek: null,
    within30DayPlan: false,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 300,
  },
  {
    skillCode: "phrase_business_coord",
    category: "phrase",
    subCategory: "workplace",
    labelZh: "業務協調片語",
    labelEn: "Business coordination phrases",
    priority: "P2",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 3,
    part6Frequency: 3,
    part7Frequency: 3,
    parentSkillKey: "vocabulary.formal-register",
    recommendedWeek: null,
    within30DayPlan: false,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 301,
  },
  {
    skillCode: "phrase_meetings",
    category: "phrase",
    subCategory: "workplace",
    labelZh: "商務會議片語",
    labelEn: "Business meeting phrases",
    priority: "P2",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 3,
    part6Frequency: 3,
    part7Frequency: 3,
    parentSkillKey: "vocabulary.formal-register",
    recommendedWeek: null,
    within30DayPlan: false,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 302,
  },
  {
    skillCode: "phrase_corporate",
    category: "phrase",
    subCategory: "workplace",
    labelZh: "企業經營片語",
    labelEn: "Corporate operation phrases",
    priority: "P2",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 3,
    part6Frequency: 3,
    part7Frequency: 3,
    parentSkillKey: "vocabulary.formal-register",
    recommendedWeek: null,
    within30DayPlan: false,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 303,
  },
  {
    skillCode: "phrase_problem_solving",
    category: "phrase",
    subCategory: "daily_function",
    labelZh: "問題解決用語",
    labelEn: "Problem-solving phrases",
    priority: "P2",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 2,
    part6Frequency: 3,
    part7Frequency: 3,
    parentSkillKey: "vocabulary.formal-register",
    recommendedWeek: null,
    within30DayPlan: false,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 310,
  },
  {
    skillCode: "phrase_decisions",
    category: "phrase",
    subCategory: "daily_function",
    labelZh: "決策表達",
    labelEn: "Decision-making phrases",
    priority: "P2",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 2,
    part6Frequency: 3,
    part7Frequency: 3,
    parentSkillKey: "vocabulary.formal-register",
    recommendedWeek: null,
    within30DayPlan: false,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 311,
  },
  {
    skillCode: "phrase_time_scheduling",
    category: "phrase",
    subCategory: "daily_function",
    labelZh: "時間排程",
    labelEn: "Time scheduling phrases",
    priority: "P2",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 3,
    part6Frequency: 3,
    part7Frequency: 3,
    parentSkillKey: "vocabulary.formal-register",
    recommendedWeek: null,
    within30DayPlan: false,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 312,
  },
  {
    skillCode: "phrase_numbers_data",
    category: "phrase",
    subCategory: "daily_function",
    labelZh: "數字與數據",
    labelEn: "Numbers & data phrases",
    priority: "P2",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 3,
    part6Frequency: 3,
    part7Frequency: 3,
    parentSkillKey: "vocabulary.formal-register",
    recommendedWeek: null,
    within30DayPlan: false,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 313,
  },
  {
    skillCode: "phrase_customer_service",
    category: "phrase",
    subCategory: "daily_function",
    labelZh: "客戶服務用語",
    labelEn: "Customer service phrases",
    priority: "P3",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 2,
    part6Frequency: 3,
    part7Frequency: 3,
    parentSkillKey: "vocabulary.formal-register",
    recommendedWeek: null,
    within30DayPlan: false,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 320,
  },
  {
    skillCode: "phrase_opinions",
    category: "phrase",
    subCategory: "daily_function",
    labelZh: "意見表達",
    labelEn: "Opinion phrases",
    priority: "P3",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 2,
    part6Frequency: 3,
    part7Frequency: 3,
    parentSkillKey: "vocabulary.formal-register",
    recommendedWeek: null,
    within30DayPlan: false,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 321,
  },
];

// ─────────────────────────────────────────────
//  STRATEGY (8 rows)
// ─────────────────────────────────────────────
const STRATEGY_SKILLS: LearningSkillSeed[] = [
  {
    skillCode: "strat_p5_timing",
    category: "strategy",
    subCategory: "exam_technique",
    labelZh: "Part 5 時間分配",
    labelEn: "Part 5 time budget (20s / item)",
    priority: "P2",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 5,
    part6Frequency: 0,
    part7Frequency: 0,
    parentSkillKey: null,
    recommendedWeek: 4,
    within30DayPlan: true,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 400,
  },
  {
    skillCode: "strat_p5_eliminate",
    category: "strategy",
    subCategory: "exam_technique",
    labelZh: "Part 5 選項消除法",
    labelEn: "Part 5 elimination (part-of-speech first)",
    priority: "P2",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 5,
    part6Frequency: 0,
    part7Frequency: 0,
    parentSkillKey: null,
    recommendedWeek: 3,
    within30DayPlan: true,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 401,
  },
  {
    skillCode: "strat_p6_flow",
    category: "strategy",
    subCategory: "reading_skill",
    labelZh: "Part 6 段落流暢策略",
    labelEn: "Part 6 discourse-flow strategy",
    priority: "P2",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 0,
    part6Frequency: 5,
    part7Frequency: 0,
    parentSkillKey: null,
    recommendedWeek: 4,
    within30DayPlan: true,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 402,
  },
  {
    skillCode: "strat_p7_skim",
    category: "strategy",
    subCategory: "reading_skill",
    labelZh: "Part 7 掃讀技巧",
    labelEn: "Part 7 skimming (main-topic first)",
    priority: "P3",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 0,
    part6Frequency: 0,
    part7Frequency: 5,
    parentSkillKey: null,
    recommendedWeek: null,
    within30DayPlan: false,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 410,
  },
  {
    skillCode: "strat_p7_scan",
    category: "strategy",
    subCategory: "reading_skill",
    labelZh: "Part 7 定位關鍵字",
    labelEn: "Part 7 scanning (keyword anchor)",
    priority: "P3",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 0,
    part6Frequency: 0,
    part7Frequency: 5,
    parentSkillKey: null,
    recommendedWeek: null,
    within30DayPlan: false,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 411,
  },
  {
    skillCode: "strat_listen_prediction",
    category: "strategy",
    subCategory: "listening_skill",
    labelZh: "聽力預測",
    labelEn: "Listening prediction (pre-read questions)",
    priority: "P3",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 0,
    part6Frequency: 0,
    part7Frequency: 0,
    parentSkillKey: null,
    recommendedWeek: null,
    within30DayPlan: false,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 420,
  },
  {
    skillCode: "strat_listen_paraphrase",
    category: "strategy",
    subCategory: "listening_skill",
    labelZh: "同義改述",
    labelEn: "Listening paraphrase recognition",
    priority: "P3",
    difficultyBand: "intermediate",
    toeicScoreBand: "500-700",
    part5Frequency: 0,
    part6Frequency: 0,
    part7Frequency: 0,
    parentSkillKey: null,
    recommendedWeek: null,
    within30DayPlan: false,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 421,
  },
  {
    skillCode: "strat_exam_endurance",
    category: "strategy",
    subCategory: "exam_technique",
    labelZh: "2 小時耐力",
    labelEn: "Full-exam 2-hour endurance",
    priority: "P4",
    difficultyBand: "advanced",
    toeicScoreBand: "700-850",
    part5Frequency: 3,
    part6Frequency: 3,
    part7Frequency: 4,
    parentSkillKey: null,
    recommendedWeek: null,
    within30DayPlan: false,
    learnPrereqJson: null,
    learnUnlocksJson: null,
    orderIndex: 430,
  },
];

export const LEARNING_SKILLS_SEED: LearningSkillSeed[] = [
  ...GRAMMAR_SKILLS,
  ...VOCABULARY_SKILLS,
  ...PHRASE_SKILLS,
  ...STRATEGY_SKILLS,
];

if (LEARNING_SKILLS_SEED.length !== 58) {
  throw new Error(
    `LEARNING_SKILLS_SEED expected 58 rows, got ${LEARNING_SKILLS_SEED.length}`,
  );
}
