import type { QuestionCorrectAnswer, QuestionDifficulty } from "../../src/lib/question-fields";
import { formatQuestionNotes, type QuestionCategory } from "../../src/lib/question-taxonomy";

type DraftQuestion = {
  category: QuestionCategory;
  subFocus: string;
  topic: string;
  difficulty: QuestionDifficulty;
  questionText: string;
  optionA: string;
  optionB: string;
  optionC: string;
  optionD: string;
  correctAnswer: QuestionCorrectAnswer;
  explanation: string;
  priorKnown?: boolean | null;
};

type BankRow = {
  questionText: string;
  optionA: string;
  optionB: string;
  optionC: string;
  optionD: string;
  correctAnswer: QuestionCorrectAnswer;
  explanation: string;
  topic: string;
  difficulty: QuestionDifficulty;
  notes: string;
  priorKnown: boolean | null;
};

export type Phase1BankSummary = {
  total: number;
  byCategory: Record<QuestionCategory, number>;
  byDifficulty: Record<QuestionDifficulty, number>;
  byTopic: Record<string, number>;
};

const TOPIC = {
  office: "文書作業 / Office Admin",
  notices: "公告訊息 / Announcements",
  meetings: "商務會議 / Business Meetings",
  coordination: "業務協調 / Coordination",
  hr: "人事與招募 / HR & Recruitment",
  finance: "財務會計 / Finance & Accounting",
  operations: "企業經營 / Business Operations",
  marketing: "行銷與宣傳 / Marketing & Sales",
  logistics: "貿易物流 / Trade & Logistics",
  tech: "科技系統 / Technology & Systems",
  communication: "溝通表達 / Communication",
  healthEnv: "醫療環境 / Health & Environment",
  daily: "日常生活 / Daily Life & Travel",
} as const;

function makeDraft(input: DraftQuestion): DraftQuestion {
  return input;
}

const vocabularyDrafts: DraftQuestion[] = [
  makeDraft({
    category: "Vocabulary",
    subFocus: "片語動詞 / Phrasal verbs",
    topic: TOPIC.office,
    difficulty: "A",
    questionText: "All interns must ___ their signed confidentiality forms before receiving network access.",
    optionA: "hand in",
    optionB: "take over",
    optionC: "break down",
    optionD: "carry on",
    correctAnswer: "A",
    explanation: "hand in 表示「提交」表格，最符合新員工交文件的情境。",
    priorKnown: false,
  }),
  makeDraft({
    category: "Vocabulary",
    subFocus: "片語動詞 / Phrasal verbs",
    topic: TOPIC.office,
    difficulty: "A",
    questionText: "Please ___ the revised contract summary before the client joins the call.",
    optionA: "call off",
    optionB: "look over",
    optionC: "drop by",
    optionD: "turn back",
    correctAnswer: "B",
    explanation: "look over 表示「快速查看、審閱」，最符合通話前先看合約摘要。",
    priorKnown: false,
  }),
  makeDraft({
    category: "Vocabulary",
    subFocus: "固定搭配 / Fixed expressions",
    topic: TOPIC.office,
    difficulty: "B",
    questionText: "The legal assistant was asked to ___ a short agreement for the temporary vendor.",
    optionA: "show off",
    optionB: "run into",
    optionC: "draw up",
    optionD: "go by",
    correctAnswer: "C",
    explanation: "draw up 常用來表示「起草、擬定」合約或文件。",
    priorKnown: false,
  }),
  makeDraft({
    category: "Vocabulary",
    subFocus: "固定搭配 / Fixed expressions",
    topic: TOPIC.office,
    difficulty: "B",
    questionText: "The project lead will ___ the implementation steps in a one-page memo.",
    optionA: "lay out",
    optionB: "set off",
    optionC: "call on",
    optionD: "turn in",
    correctAnswer: "A",
    explanation: "lay out 表示「清楚列出、安排說明」，常見於 memo 或計畫步驟說明。",
    priorKnown: false,
  }),
  makeDraft({
    category: "Vocabulary",
    subFocus: "正式書面語 / Formal register",
    topic: TOPIC.office,
    difficulty: "C",
    questionText: "Please contact Ms. Huang ___ the revised warranty clause.",
    optionA: "out of stock",
    optionB: "with regard to",
    optionC: "in charge of",
    optionD: "on the contrary",
    correctAnswer: "B",
    explanation: "with regard to 是正式書面語，表示「關於」。",
    priorKnown: false,
  }),
  makeDraft({
    category: "Vocabulary",
    subFocus: "片語動詞 / Phrasal verbs",
    topic: TOPIC.office,
    difficulty: "A",
    questionText: "Before sending the bid, the analyst should ___ every figure in the spreadsheet.",
    optionA: "break even",
    optionB: "put aside",
    optionC: "check over",
    optionD: "turn over",
    correctAnswer: "C",
    explanation: "check over 表示「仔細檢查」，最適合核對試算表數字。",
    priorKnown: false,
  }),
  makeDraft({
    category: "Vocabulary",
    subFocus: "正式書面語 / Formal register",
    topic: TOPIC.notices,
    difficulty: "C",
    questionText: "Parking permits must be displayed ___ the building's updated safety policy.",
    optionA: "on behalf of",
    optionB: "at your earliest convenience",
    optionC: "in accordance with",
    optionD: "out of office",
    correctAnswer: "C",
    explanation: "in accordance with 表示「依照、按照」，常用於公告與政策語境。",
    priorKnown: false,
  }),
  makeDraft({
    category: "Vocabulary",
    subFocus: "正式書面語 / Formal register",
    topic: TOPIC.notices,
    difficulty: "C",
    questionText: "___ the typhoon warning, tomorrow's client visits will be rescheduled.",
    optionA: "In light of",
    optionB: "On behalf of",
    optionC: "At your earliest convenience",
    optionD: "Out of stock",
    correctAnswer: "A",
    explanation: "in light of 表示「鑑於、考量到」，適合用在根據外部情況調整安排。",
    priorKnown: false,
  }),
  makeDraft({
    category: "Vocabulary",
    subFocus: "正式書面語 / Formal register",
    topic: TOPIC.notices,
    difficulty: "C",
    questionText: "___ a power failure, staff should use the stairwell instead of the elevator.",
    optionA: "In charge of",
    optionB: "On the verge of",
    optionC: "In the event of",
    optionD: "On behalf of",
    correctAnswer: "C",
    explanation: "in the event of 表示「如果發生、萬一」，常見於安全公告。",
    priorKnown: false,
  }),
  makeDraft({
    category: "Vocabulary",
    subFocus: "商務搭配 / Business collocation",
    topic: TOPIC.notices,
    difficulty: "B",
    questionText: "The revised travel policy may ___ additional approvals for overseas trips.",
    optionA: "look into",
    optionB: "call for",
    optionC: "put off",
    optionD: "run out of",
    correctAnswer: "B",
    explanation: "call for 在此表示「需要、要求」，常用於政策或程序要求。",
    priorKnown: false,
  }),
  makeDraft({
    category: "Vocabulary",
    subFocus: "片語動詞 / Phrasal verbs",
    topic: TOPIC.meetings,
    difficulty: "B",
    questionText: "Please do not ___ unrelated budget concerns during the short safety briefing.",
    optionA: "carry over",
    optionB: "bring up",
    optionC: "fall under",
    optionD: "pay back",
    correctAnswer: "B",
    explanation: "bring up 表示「提出話題」，最符合會議中提起其他議題的情境。",
    priorKnown: false,
  }),
  makeDraft({
    category: "Vocabulary",
    subFocus: "固定搭配 / Fixed expressions",
    topic: TOPIC.meetings,
    difficulty: "C",
    questionText: "The board did not ___ a regional expansion, but asked for more data first.",
    optionA: "rule out",
    optionB: "fill in",
    optionC: "count on",
    optionD: "pay for",
    correctAnswer: "A",
    explanation: "rule out 表示「排除、不考慮」，與董事會暫未排除某方案的語境吻合。",
    priorKnown: false,
  }),
  makeDraft({
    category: "Vocabulary",
    subFocus: "固定搭配 / Fixed expressions",
    topic: TOPIC.meetings,
    difficulty: "B",
    questionText: "As we compare the proposals, please ___ the vendor's after-sales support.",
    optionA: "show off",
    optionB: "bear in mind",
    optionC: "back out",
    optionD: "move away",
    correctAnswer: "B",
    explanation: "bear in mind 表示「記住、牢記」，適合提醒比較提案時要考慮某因素。",
    priorKnown: false,
  }),
  makeDraft({
    category: "Vocabulary",
    subFocus: "固定搭配 / Fixed expressions",
    topic: TOPIC.meetings,
    difficulty: "B",
    questionText: "After a long discussion, the committee finally ___ a single launch date.",
    optionA: "went over",
    optionB: "handed over",
    optionC: "settled on",
    optionD: "backed out",
    correctAnswer: "C",
    explanation: "settle on 表示「最終決定採用」，常見於討論後拍板。",
    priorKnown: false,
  }),
  makeDraft({
    category: "Vocabulary",
    subFocus: "片語動詞 / Phrasal verbs",
    topic: TOPIC.coordination,
    difficulty: "B",
    questionText: "The operations team will ___ the inventory count after business hours.",
    optionA: "carry out",
    optionB: "break away from",
    optionC: "cut back on",
    optionD: "put aside",
    correctAnswer: "A",
    explanation: "carry out 表示「執行」，最符合執行盤點工作。",
    priorKnown: false,
  }),
  makeDraft({
    category: "Vocabulary",
    subFocus: "固定搭配 / Fixed expressions",
    topic: TOPIC.coordination,
    difficulty: "B",
    questionText: "Mr. Chan will ___ the room setup while I confirm the guest list.",
    optionA: "speak of",
    optionB: "see to",
    optionC: "tune in",
    optionD: "break even",
    correctAnswer: "B",
    explanation: "see to 表示「負責處理、照料」，很適合會前分工。",
    priorKnown: false,
  }),
  makeDraft({
    category: "Vocabulary",
    subFocus: "固定搭配 / Fixed expressions",
    topic: TOPIC.coordination,
    difficulty: "B",
    questionText: "To avoid confusion, everyone should ___ the approved slide deck.",
    optionA: "break through",
    optionB: "go by",
    optionC: "stick to",
    optionD: "write off",
    correctAnswer: "C",
    explanation: "stick to 表示「遵守、照著做」，符合簡報統一版本的要求。",
    priorKnown: false,
  }),
  makeDraft({
    category: "Vocabulary",
    subFocus: "商務搭配 / Business collocation",
    topic: TOPIC.hr,
    difficulty: "B",
    questionText: "The recruiter used the phone screen to ___ the list of applicants.",
    optionA: "print out",
    optionB: "narrow down",
    optionC: "take back",
    optionD: "line up",
    correctAnswer: "B",
    explanation: "narrow down 表示「縮小範圍、篩選」，常用在招募流程。",
    priorKnown: false,
  }),
  makeDraft({
    category: "Vocabulary",
    subFocus: "商務搭配 / Business collocation",
    topic: TOPIC.hr,
    difficulty: "B",
    questionText: "Candidates with bilingual presentation skills tend to ___ during the final interview.",
    optionA: "fall through",
    optionB: "draw on",
    optionC: "come under",
    optionD: "stand out",
    correctAnswer: "D",
    explanation: "stand out 表示「脫穎而出」，很常用在面試或競爭情境。",
    priorKnown: false,
  }),
  makeDraft({
    category: "Vocabulary",
    subFocus: "商務搭配 / Business collocation",
    topic: TOPIC.finance,
    difficulty: "B",
    questionText: "Fuel costs now ___ nearly fifteen percent of the department budget.",
    optionA: "live on",
    optionB: "account for",
    optionC: "aim at",
    optionD: "go through",
    correctAnswer: "B",
    explanation: "account for 可表示「占比、占去」，很常出現在財務描述。",
    priorKnown: false,
  }),
  makeDraft({
    category: "Vocabulary",
    subFocus: "正式書面語 / Formal register",
    topic: TOPIC.finance,
    difficulty: "C",
    questionText: "The estimate does not fully ___ customs fees and storage charges.",
    optionA: "take into account",
    optionB: "break out of",
    optionC: "stand by",
    optionD: "move up",
    correctAnswer: "A",
    explanation: "take into account 表示「納入考量」，常見於預算與估算場景。",
    priorKnown: false,
  }),
  makeDraft({
    category: "Vocabulary",
    subFocus: "正式書面語 / Formal register",
    topic: TOPIC.finance,
    difficulty: "C",
    questionText: "After the service surcharge was added, the final bill ___ more than NT$48,000.",
    optionA: "complied with",
    optionB: "spoke with",
    optionC: "turned back",
    optionD: "amounted to",
    correctAnswer: "D",
    explanation: "amount to 表示「總計達到」，是正式財務與數字描述常用語。",
    priorKnown: false,
  }),
  makeDraft({
    category: "Vocabulary",
    subFocus: "商務搭配 / Business collocation",
    topic: TOPIC.operations,
    difficulty: "B",
    questionText: "The factory plans to ___ the older inspection system over two quarters.",
    optionA: "phase out",
    optionB: "log on",
    optionC: "set off",
    optionD: "take up",
    correctAnswer: "A",
    explanation: "phase out 表示「逐步淘汰」，最符合舊系統退場的情境。",
    priorKnown: false,
  }),
  makeDraft({
    category: "Vocabulary",
    subFocus: "商務搭配 / Business collocation",
    topic: TOPIC.operations,
    difficulty: "B",
    questionText: "The company will ___ the new approval workflow team by team next month.",
    optionA: "sort out",
    optionB: "phase in",
    optionC: "give out",
    optionD: "look after",
    correctAnswer: "B",
    explanation: "phase in 表示「逐步導入」，與新流程分批上線完全吻合。",
    priorKnown: false,
  }),
  makeDraft({
    category: "Vocabulary",
    subFocus: "商務搭配 / Business collocation",
    topic: TOPIC.marketing,
    difficulty: "B",
    questionText: "The marketing team needs to ___ a clearer social media plan for the product launch.",
    optionA: "pass on",
    optionB: "map out",
    optionC: "keep with",
    optionD: "write back",
    correctAnswer: "B",
    explanation: "map out 表示「規劃、畫出方向」，很適合用於行銷計畫。",
    priorKnown: false,
  }),
  makeDraft({
    category: "Vocabulary",
    subFocus: "商務搭配 / Business collocation",
    topic: TOPIC.marketing,
    difficulty: "C",
    questionText: "The new ad campaign is meant to ___ first-time buyers in smaller cities.",
    optionA: "hand back",
    optionB: "break up",
    optionC: "tap into",
    optionD: "answer to",
    correctAnswer: "C",
    explanation: "tap into 表示「開發、利用某市場或資源」，常用於行銷受眾擴張。",
    priorKnown: false,
  }),
  makeDraft({
    category: "Vocabulary",
    subFocus: "片語動詞 / Phrasal verbs",
    topic: TOPIC.tech,
    difficulty: "A",
    questionText: "Please ___ the service logs before installing the new patch.",
    optionA: "point out",
    optionB: "shut down",
    optionC: "back up",
    optionD: "work out",
    correctAnswer: "C",
    explanation: "back up 表示「備份」，是安裝更新前最合理的動作。",
    priorKnown: false,
  }),
  makeDraft({
    category: "Vocabulary",
    subFocus: "固定搭配 / Fixed expressions",
    topic: TOPIC.tech,
    difficulty: "B",
    questionText: "Field engineers must ___ frequent firmware changes across several tool lines.",
    optionA: "set aside",
    optionB: "keep up with",
    optionC: "call on",
    optionD: "fill out",
    correctAnswer: "B",
    explanation: "keep up with 表示「跟上」，很適合描述工程師追蹤更新變化。",
    priorKnown: false,
  }),
  makeDraft({
    category: "Vocabulary",
    subFocus: "正式書面語 / Formal register",
    topic: TOPIC.communication,
    difficulty: "B",
    questionText: "Her first draft was accurate, but it did not clearly ___ the urgency of the request.",
    optionA: "see through",
    optionB: "put across",
    optionC: "knock down",
    optionD: "check in",
    correctAnswer: "B",
    explanation: "put across 表示「清楚表達、讓人理解」，常見於溝通品質描述。",
    priorKnown: false,
  }),
  makeDraft({
    category: "Vocabulary",
    subFocus: "正式書面語 / Formal register",
    topic: TOPIC.healthEnv,
    difficulty: "C",
    questionText: "Technicians must ___ chemical waste using the approved procedure.",
    optionA: "turn out",
    optionB: "count toward",
    optionC: "dispose of",
    optionD: "think of",
    correctAnswer: "C",
    explanation: "dispose of 表示「處理掉、處置」，很常出現在安全與環保規範。",
    priorKnown: false,
  }),
  makeDraft({
    category: "Vocabulary",
    subFocus: "抽象字義 / Abstract meaning",
    topic: TOPIC.communication,
    difficulty: "B",
    questionText: "Reply-all should be used with care because poor e-mail ___ can annoy clients.",
    optionA: "etiquette",
    optionB: "itinerary",
    optionC: "subsidy",
    optionD: "pollutant",
    correctAnswer: "A",
    explanation: "etiquette 表示「禮儀、得體做法」，最符合 e-mail 使用規矩的語境。",
    priorKnown: false,
  }),
  makeDraft({
    category: "Vocabulary",
    subFocus: "領域字彙 / Domain vocabulary",
    topic: TOPIC.healthEnv,
    difficulty: "C",
    questionText: "The report warned that the nearby stream had been affected by an industrial ___.",
    optionA: "orchestra",
    optionB: "laminator",
    optionC: "pantry",
    optionD: "pollutant",
    correctAnswer: "D",
    explanation: "pollutant 表示「污染物」，最符合環境污染報告的描述。",
    priorKnown: false,
  }),
  makeDraft({
    category: "Vocabulary",
    subFocus: "商務搭配 / Business collocation",
    topic: TOPIC.hr,
    difficulty: "A",
    questionText: "New hires should ___ the orientation workshop no later than Friday afternoon.",
    optionA: "sign up for",
    optionB: "turn down",
    optionC: "break away from",
    optionD: "add up",
    correctAnswer: "A",
    explanation: "sign up for 表示「報名參加」，這題屬於較穩定的基礎強項，保留少量作為 reinforcement。",
    priorKnown: true,
  }),
  makeDraft({
    category: "Vocabulary",
    subFocus: "商務搭配 / Business collocation",
    topic: TOPIC.coordination,
    difficulty: "A",
    questionText: "You can ___ Jenny to update the dispatch board before the drivers arrive.",
    optionA: "bring about",
    optionB: "count on",
    optionC: "phase in",
    optionD: "see through",
    correctAnswer: "B",
    explanation: "count on 表示「可以依靠」，屬於背景中較穩的基礎搭配。",
    priorKnown: true,
  }),
  makeDraft({
    category: "Vocabulary",
    subFocus: "商務搭配 / Business collocation",
    topic: TOPIC.coordination,
    difficulty: "A",
    questionText: "Please ___ the supplier's complaint after you confirm the damaged quantity.",
    optionA: "follow up on",
    optionB: "rule on",
    optionC: "hold on",
    optionD: "take part in",
    correctAnswer: "A",
    explanation: "follow up on 表示「跟進」，屬於應保留的較強區基礎商務搭配。",
    priorKnown: true,
  }),
  makeDraft({
    category: "Vocabulary",
    subFocus: "商務搭配 / Business collocation",
    topic: TOPIC.coordination,
    difficulty: "A",
    questionText: "Project staff must ___ the overseas vendor before changing the test schedule.",
    optionA: "benefit from",
    optionB: "stare at",
    optionC: "move up",
    optionD: "coordinate with",
    correctAnswer: "D",
    explanation: "coordinate with 表示「與…協調」，屬於使用者較能掌握的工作場景語彙。",
    priorKnown: true,
  }),
  makeDraft({
    category: "Vocabulary",
    subFocus: "商務搭配 / Business collocation",
    topic: TOPIC.logistics,
    difficulty: "A",
    questionText: "The branch usually ___ this supplier when it needs extra packing cartons.",
    optionA: "order from",
    optionB: "result in",
    optionC: "take over",
    optionD: "sign off",
    correctAnswer: "A",
    explanation: "order from 表示「向…訂購」，屬於相對穩定的物流基礎搭配。",
    priorKnown: true,
  }),
  makeDraft({
    category: "Vocabulary",
    subFocus: "商務搭配 / Business collocation",
    topic: TOPIC.finance,
    difficulty: "A",
    questionText: "The company plans to ___ additional testing equipment before the new contract starts.",
    optionA: "refer to",
    optionB: "care for",
    optionC: "invest in",
    optionD: "pass along",
    correctAnswer: "C",
    explanation: "invest in 表示「投資於」，對應背景中較穩的金融概念區。",
    priorKnown: true,
  }),
  makeDraft({
    category: "Vocabulary",
    subFocus: "商務搭配 / Business collocation",
    topic: TOPIC.operations,
    difficulty: "A",
    questionText: "Regional managers need to ___ extra hiring costs before approving the expansion.",
    optionA: "recover from",
    optionB: "belong to",
    optionC: "come by",
    optionD: "plan for",
    correctAnswer: "D",
    explanation: "plan for 表示「為…做規劃」，屬於較穩的企業經營基礎搭配。",
    priorKnown: true,
  }),
  makeDraft({
    category: "Vocabulary",
    subFocus: "商務搭配 / Business collocation",
    topic: TOPIC.daily,
    difficulty: "A",
    questionText: "The purchasing clerk cannot promise same-day delivery because the printer cartridges are ___.",
    optionA: "in charge of",
    optionB: "out of stock",
    optionC: "on the verge of",
    optionD: "at your earliest convenience",
    correctAnswer: "B",
    explanation: "out of stock 表示「缺貨」，屬於應保留的低難度穩定字彙。",
    priorKnown: true,
  }),
];
const grammarDrafts: DraftQuestion[] = [
  makeDraft({
    category: "Grammar",
    subFocus: "動詞時態 / Verb tense",
    topic: TOPIC.tech,
    difficulty: "A",
    questionText: "The maintenance team usually ___ the safety checklist before each startup.",
    optionA: "reviews",
    optionB: "reviewed",
    optionC: "is reviewing",
    optionD: "has reviewed",
    correctAnswer: "A",
    explanation: "usually 表示習慣動作，所以用一般現在式 reviews。",
  }),
  makeDraft({
    category: "Grammar",
    subFocus: "動詞時態 / Verb tense",
    topic: TOPIC.tech,
    difficulty: "B",
    questionText: "Since the vendor updated the firmware, the error message ___ less frequently.",
    optionA: "appeared",
    optionB: "has appeared",
    optionC: "appears",
    optionD: "appearing",
    correctAnswer: "B",
    explanation: "since 引出從過去持續到現在的結果，這裡用現在完成式 has appeared。",
  }),
  makeDraft({
    category: "Grammar",
    subFocus: "動詞時態 / Verb tense",
    topic: TOPIC.finance,
    difficulty: "A",
    questionText: "The regional manager ___ the revised budget yesterday afternoon.",
    optionA: "approves",
    optionB: "approving",
    optionC: "approved",
    optionD: "has approved",
    correctAnswer: "C",
    explanation: "yesterday afternoon 是明確過去時間，所以用過去式 approved。",
  }),
  makeDraft({
    category: "Grammar",
    subFocus: "動詞時態 / Verb tense",
    topic: TOPIC.operations,
    difficulty: "B",
    questionText: "If the parts arrive on time, the plant ___ full production next Monday.",
    optionA: "resumed",
    optionB: "resumes",
    optionC: "has resumed",
    optionD: "will resume",
    correctAnswer: "D",
    explanation: "條件句主句表示未來結果時，用 will resume。",
  }),
  makeDraft({
    category: "Grammar",
    subFocus: "動詞時態 / Verb tense",
    topic: TOPIC.finance,
    difficulty: "C",
    questionText: "By the end of this quarter, the finance team ___ three rounds of cost reviews.",
    optionA: "completed",
    optionB: "completes",
    optionC: "will have completed",
    optionD: "had completed",
    correctAnswer: "C",
    explanation: "by the end of this quarter 表示到未來某時點前完成，用 future perfect：will have completed。",
  }),
  makeDraft({
    category: "Grammar",
    subFocus: "動詞時態 / Verb tense",
    topic: TOPIC.office,
    difficulty: "B",
    questionText: "Before the auditor arrived, the controller ___ all supporting files into one folder.",
    optionA: "gathers",
    optionB: "has gathered",
    optionC: "will gather",
    optionD: "had gathered",
    correctAnswer: "D",
    explanation: "在 auditor arrived 之前已完成的動作用過去完成式 had gathered。",
  }),
  makeDraft({
    category: "Grammar",
    subFocus: "被動語態 / Passive voice",
    topic: TOPIC.finance,
    difficulty: "A",
    questionText: "All reimbursement forms must ___ electronically through the new portal.",
    optionA: "submitted",
    optionB: "be submitted",
    optionC: "be submitting",
    optionD: "have submitted",
    correctAnswer: "B",
    explanation: "must 後接被動時要用 must be + past participle，因此是 be submitted。",
  }),
  makeDraft({
    category: "Grammar",
    subFocus: "被動語態 / Passive voice",
    topic: TOPIC.hr,
    difficulty: "A",
    questionText: "The training schedule was ___ to every department head on Friday.",
    optionA: "sends",
    optionB: "send",
    optionC: "sent",
    optionD: "sending",
    correctAnswer: "C",
    explanation: "was 後面需要過去分詞形成被動語態，所以用 sent。",
  }),
  makeDraft({
    category: "Grammar",
    subFocus: "被動語態 / Passive voice",
    topic: TOPIC.logistics,
    difficulty: "A",
    questionText: "The damaged parts should ___ in a separate cabinet until inspection is finished.",
    optionA: "store",
    optionB: "stored",
    optionC: "be stored",
    optionD: "be storing",
    correctAnswer: "C",
    explanation: "should 的被動形式是 should be + past participle，所以選 be stored。",
  }),
  makeDraft({
    category: "Grammar",
    subFocus: "被動語態 / Passive voice",
    topic: TOPIC.office,
    difficulty: "C",
    questionText: "The final contract has not been ___ by the legal department yet.",
    optionA: "approved",
    optionB: "approve",
    optionC: "approving",
    optionD: "approves",
    correctAnswer: "A",
    explanation: "has not been 後面要接過去分詞 approved，形成現在完成被動。",
  }),
  makeDraft({
    category: "Grammar",
    subFocus: "主詞動詞一致 / Subject-Verb Agreement",
    topic: TOPIC.office,
    difficulty: "A",
    questionText: "Each of the service reports ___ a manager's signature before filing.",
    optionA: "require",
    optionB: "requires",
    optionC: "requiring",
    optionD: "are requiring",
    correctAnswer: "B",
    explanation: "each 作主詞時視為單數，所以動詞要用 requires。",
  }),
  makeDraft({
    category: "Grammar",
    subFocus: "主詞動詞一致 / Subject-Verb Agreement",
    topic: TOPIC.hr,
    difficulty: "B",
    questionText: "Neither the branch manager nor the assistants ___ available for the late call.",
    optionA: "was",
    optionB: "were",
    optionC: "be",
    optionD: "has been",
    correctAnswer: "B",
    explanation: "neither...nor... 通常與靠近動詞的主詞一致；assistants 是複數，所以用 were。",
  }),
  makeDraft({
    category: "Grammar",
    subFocus: "主詞動詞一致 / Subject-Verb Agreement",
    topic: TOPIC.hr,
    difficulty: "A",
    questionText: "One of the new interns ___ fluent Japanese and can support the Osaka client team.",
    optionA: "are",
    optionB: "is",
    optionC: "have been",
    optionD: "being",
    correctAnswer: "B",
    explanation: "one of + plural noun 的主詞核心是 one，所以用單數動詞 is。",
  }),
  makeDraft({
    category: "Grammar",
    subFocus: "主詞動詞一致 / Subject-Verb Agreement",
    topic: TOPIC.finance,
    difficulty: "C",
    questionText: "A list of unresolved claims ___ attached to the e-mail for your reference.",
    optionA: "are",
    optionB: "have",
    optionC: "be",
    optionD: "is",
    correctAnswer: "D",
    explanation: "真正主詞是 a list，屬單數，所以用 is attached。",
  }),
  makeDraft({
    category: "Grammar",
    subFocus: "動名詞與不定詞 / Gerund vs. Infinitive",
    topic: TOPIC.operations,
    difficulty: "A",
    questionText: "The director decided ___ the launch until the supplier confirmed the new date.",
    optionA: "to postpone",
    optionB: "postponing",
    optionC: "postpone",
    optionD: "postponed",
    correctAnswer: "A",
    explanation: "decide 後面接 to-infinitive，所以是 to postpone。",
  }),
  makeDraft({
    category: "Grammar",
    subFocus: "動名詞與不定詞 / Gerund vs. Infinitive",
    topic: TOPIC.notices,
    difficulty: "A",
    questionText: "All visitors are required ___ their badges at the reception desk.",
    optionA: "wearing",
    optionB: "wear",
    optionC: "to wear",
    optionD: "wore",
    correctAnswer: "C",
    explanation: "be required 後面接 to-infinitive，因此選 to wear。",
  }),
  makeDraft({
    category: "Grammar",
    subFocus: "動名詞與不定詞 / Gerund vs. Infinitive",
    topic: TOPIC.meetings,
    difficulty: "B",
    questionText: "The committee postponed ___ a final recommendation until next week.",
    optionA: "to make",
    optionB: "make",
    optionC: "made",
    optionD: "making",
    correctAnswer: "D",
    explanation: "postpone 後面接動名詞，所以是 making。",
  }),
  makeDraft({
    category: "Grammar",
    subFocus: "動名詞與不定詞 / Gerund vs. Infinitive",
    topic: TOPIC.communication,
    difficulty: "A",
    questionText: "We look forward to ___ your detailed proposal after the site visit.",
    optionA: "receiving",
    optionB: "receive",
    optionC: "received",
    optionD: "to receive",
    correctAnswer: "A",
    explanation: "look forward to 的 to 是介系詞，後面要接動名詞 receiving。",
  }),
  makeDraft({
    category: "Grammar",
    subFocus: "介系詞與固定搭配 / Prepositions & patterns",
    topic: TOPIC.coordination,
    difficulty: "A",
    questionText: "Ms. Lau is responsible ___ negotiating the annual service contract.",
    optionA: "for",
    optionB: "to",
    optionC: "at",
    optionD: "by",
    correctAnswer: "A",
    explanation: "responsible 的固定搭配是 responsible for。",
  }),
  makeDraft({
    category: "Grammar",
    subFocus: "介系詞與固定搭配 / Prepositions & patterns",
    topic: TOPIC.finance,
    difficulty: "A",
    questionText: "Several investors are interested ___ the company's clean-energy expansion plan.",
    optionA: "on",
    optionB: "for",
    optionC: "with",
    optionD: "in",
    correctAnswer: "D",
    explanation: "be interested in 是固定搭配，所以用 in。",
  }),
  makeDraft({
    category: "Grammar",
    subFocus: "介系詞與固定搭配 / Prepositions & patterns",
    topic: TOPIC.logistics,
    difficulty: "A",
    questionText: "The delivery time depends ___ whether customs clears the shipment this afternoon.",
    optionA: "on",
    optionB: "of",
    optionC: "for",
    optionD: "to",
    correctAnswer: "A",
    explanation: "depend 的固定搭配是 depend on。",
  }),
  makeDraft({
    category: "Grammar",
    subFocus: "介系詞與固定搭配 / Prepositions & patterns",
    topic: TOPIC.notices,
    difficulty: "B",
    questionText: "All technicians must comply ___ the updated lockout procedure.",
    optionA: "on",
    optionB: "at",
    optionC: "from",
    optionD: "with",
    correctAnswer: "D",
    explanation: "comply 的固定搭配是 comply with，表示「遵守」。",
  }),
  makeDraft({
    category: "Grammar",
    subFocus: "關係子句 / Relative clauses",
    topic: TOPIC.hr,
    difficulty: "A",
    questionText: "The candidate ___ led the cross-border project will join the second interview round.",
    optionA: "which",
    optionB: "who",
    optionC: "whose",
    optionD: "where",
    correctAnswer: "B",
    explanation: "先行詞是 candidate（人），關係代名詞應用 who。",
  }),
  makeDraft({
    category: "Grammar",
    subFocus: "關係子句 / Relative clauses",
    topic: TOPIC.finance,
    difficulty: "A",
    questionText: "The invoice ___ was attached to the earlier e-mail shows the old unit price.",
    optionA: "that",
    optionB: "who",
    optionC: "where",
    optionD: "whose",
    correctAnswer: "A",
    explanation: "先行詞是 invoice（物），關係代名詞可用 that。",
  }),
  makeDraft({
    category: "Grammar",
    subFocus: "關係子句 / Relative clauses",
    topic: TOPIC.logistics,
    difficulty: "C",
    questionText: "The supplier ___ warehouse was flooded requested extra time for shipment.",
    optionA: "which",
    optionB: "who",
    optionC: "whose",
    optionD: "where",
    correctAnswer: "C",
    explanation: "要表達「供應商的倉庫」，關係所有格用 whose。",
  }),
  makeDraft({
    category: "Grammar",
    subFocus: "關係子句 / Relative clauses",
    topic: TOPIC.meetings,
    difficulty: "B",
    questionText: "This is the office ___ the safety seminar will be held tomorrow morning.",
    optionA: "who",
    optionB: "which",
    optionC: "whose",
    optionD: "where",
    correctAnswer: "D",
    explanation: "表示地點時用 where，引導「研討會將在那裡舉行」的關係子句。",
  }),
  makeDraft({
    category: "Grammar",
    subFocus: "連接詞與邏輯 / Conjunctions & logic",
    topic: TOPIC.communication,
    difficulty: "B",
    questionText: "___ the pilot program ended last month, the support team continues collecting feedback from users.",
    optionA: "Because",
    optionB: "Although",
    optionC: "Unless",
    optionD: "So",
    correctAnswer: "B",
    explanation: "前後語意有轉折，應用 although 表示「雖然」。",
  }),
  makeDraft({
    category: "Grammar",
    subFocus: "連接詞與邏輯 / Conjunctions & logic",
    topic: TOPIC.logistics,
    difficulty: "B",
    questionText: "The shipment was delayed ___ a customs inspection at the port.",
    optionA: "because",
    optionB: "although",
    optionC: "because of",
    optionD: "unless",
    correctAnswer: "C",
    explanation: "後面接名詞片語 a customs inspection，所以要用 because of。",
  }),
  makeDraft({
    category: "Grammar",
    subFocus: "連接詞與邏輯 / Conjunctions & logic",
    topic: TOPIC.operations,
    difficulty: "C",
    questionText: "The updated policy is intended not only to reduce delays ___ to improve data accuracy.",
    optionA: "and also",
    optionB: "also but",
    optionC: "so as",
    optionD: "but also",
    correctAnswer: "D",
    explanation: "not only ... but also ... 是固定平行結構。",
  }),
  makeDraft({
    category: "Grammar",
    subFocus: "used to 系列 / Used to family",
    topic: TOPIC.communication,
    difficulty: "B",
    questionText: "After six months in the role, Ms. Chang is finally used to ___ weekly progress briefings in English.",
    optionA: "give",
    optionB: "giving",
    optionC: "gave",
    optionD: "to give",
    correctAnswer: "B",
    explanation: "be used to 中的 to 是介系詞，後面要接動名詞 giving。",
  }),
  makeDraft({
    category: "Grammar",
    subFocus: "used to 系列 / Used to family",
    topic: TOPIC.daily,
    difficulty: "B",
    questionText: "Our former service desk manager used to ___ in Taichung before transferring to Hsinchu.",
    optionA: "working",
    optionB: "worked",
    optionC: "work",
    optionD: "be working",
    correctAnswer: "C",
    explanation: "used to 後面接原形動詞，表示「過去常常……」。",
  }),
  makeDraft({
    category: "Grammar",
    subFocus: "分詞修飾 / Participles",
    topic: TOPIC.office,
    difficulty: "B",
    questionText: "Clients were confused by the ___ instructions on the old registration page.",
    optionA: "misled",
    optionB: "misleading",
    optionC: "mislead",
    optionD: "misleads",
    correctAnswer: "B",
    explanation: "修飾 instructions 的是造成混淆的性質，所以用主動含義的 misleading。",
  }),
];
const readingDrafts: DraftQuestion[] = [
  makeDraft({
    category: "Reading",
    subFocus: "電子郵件細節 / Email detail",
    topic: TOPIC.office,
    difficulty: "A",
    questionText:
      'Email excerpt: "Please submit the signed visitor list to reception before 9:30 A.M. The courier will collect the badges at 10:00 A.M." What must staff do before 9:30 A.M.?',
    optionA: "Print extra badges",
    optionB: "Send the visitor list to reception",
    optionC: "Call the courier",
    optionD: "Move the badges to the lobby",
    correctAnswer: "B",
    explanation: "題目直接指出 staff 要在 9:30 前把 signed visitor list 交到 reception。",
  }),
  makeDraft({
    category: "Reading",
    subFocus: "公告目的 / Notice purpose",
    topic: TOPIC.notices,
    difficulty: "A",
    questionText:
      'Notice: "The west entrance will be closed this Thursday while the security gate is replaced. Please use the lobby entrance instead." What is the main purpose of the notice?',
    optionA: "To announce a change in building access",
    optionB: "To recruit more security staff",
    optionC: "To explain how to replace a gate",
    optionD: "To request feedback on the lobby design",
    correctAnswer: "A",
    explanation: "公告重點是告知西側入口暫停使用並改走大廳入口。",
  }),
  makeDraft({
    category: "Reading",
    subFocus: "會議細節 / Meeting detail",
    topic: TOPIC.meetings,
    difficulty: "A",
    questionText:
      'Memo: "Tomorrow\'s vendor meeting starts at 2:15 P.M. in Room 5B. Participants should review the pricing sheet in advance." What are participants asked to do?',
    optionA: "Arrive at Room 5A before lunch",
    optionB: "Prepare a new price quote",
    optionC: "Review the pricing sheet before the meeting",
    optionD: "Call the vendor after the meeting",
    correctAnswer: "C",
    explanation: "memo 明確要求與會者會前先 review the pricing sheet。",
  }),
  makeDraft({
    category: "Reading",
    subFocus: "工作協調細節 / Coordination detail",
    topic: TOPIC.coordination,
    difficulty: "A",
    questionText:
      'Email: "I have updated the delivery chart in the shared folder. Please confirm the red items before I send the final version to the supplier." What does the writer want the reader to do?',
    optionA: "Approve the supplier invoice",
    optionB: "Confirm the red items in the chart",
    optionC: "Create a new shared folder",
    optionD: "Print the chart for the warehouse",
    correctAnswer: "B",
    explanation: "寫信人要求對方先確認紅色項目，再把最終版送給供應商。",
  }),
  makeDraft({
    category: "Reading",
    subFocus: "人事規則細節 / HR detail",
    topic: TOPIC.hr,
    difficulty: "A",
    questionText:
      'HR message: "New employees will receive their ID cards on Monday morning. Until then, they must sign in at the front desk each day." What must new employees do before Monday morning?',
    optionA: "Collect their cards from security",
    optionB: "Work from home",
    optionC: "Sign in at the front desk",
    optionD: "Visit HR after lunch",
    correctAnswer: "C",
    explanation: "在拿到 ID card 之前，新員工每天都要到 front desk 簽到。",
  }),
  makeDraft({
    category: "Reading",
    subFocus: "財務規則細節 / Finance detail",
    topic: TOPIC.finance,
    difficulty: "A",
    questionText:
      'Finance reminder: "Expense claims filed after the 25th will be processed in the next month. Please attach original receipts to avoid delays." Why might a claim be delayed?',
    optionA: "It was submitted too late",
    optionB: "The hotel was too expensive",
    optionC: "The manager was traveling",
    optionD: "The employee used cash",
    correctAnswer: "A",
    explanation: "題目明確指出 25 號後送出的報銷單會在下個月處理。",
  }),
  makeDraft({
    category: "Reading",
    subFocus: "物流細節 / Logistics detail",
    topic: TOPIC.logistics,
    difficulty: "B",
    questionText:
      'Shipment email: "Container HX-42 reached Kaohsiung last night, but customs requested one more packing document. Delivery to the client will move to Friday unless the form is approved today." What is delaying the delivery?',
    optionA: "A missing packing document",
    optionB: "A labor strike at the warehouse",
    optionC: "A broken delivery truck",
    optionD: "A canceled client order",
    correctAnswer: "A",
    explanation: "延誤原因是 customs 還要一份 packing document。",
  }),
  makeDraft({
    category: "Reading",
    subFocus: "行銷流程細節 / Marketing detail",
    topic: TOPIC.marketing,
    difficulty: "B",
    questionText:
      'Campaign note: "The poster design was approved, but the launch will stay on hold until the online banner is localized for the Hong Kong market." What is the launch waiting for?',
    optionA: "A new product photo shoot",
    optionB: "Approval from the finance team",
    optionC: "Localized online banner content",
    optionD: "A discount request from retailers",
    correctAnswer: "C",
    explanation: "上線仍在等待 online banner 完成本地化。",
  }),
  makeDraft({
    category: "Reading",
    subFocus: "技術報告細節 / Technical detail",
    topic: TOPIC.tech,
    difficulty: "B",
    questionText:
      'Service report: "The scanner is working again after a cable replacement. However, image quality remains uneven, so the calibration visit will continue as planned." Which issue has NOT been fully resolved?',
    optionA: "The network account problem",
    optionB: "The cable replacement",
    optionC: "The image quality problem",
    optionD: "The travel booking delay",
    correctAnswer: "C",
    explanation: "scanner 已可使用，但 image quality 仍不平均，所以問題尚未完全解決。",
  }),
  makeDraft({
    category: "Reading",
    subFocus: "說話者意圖 / Writer intent",
    topic: TOPIC.communication,
    difficulty: "A",
    questionText:
      'Client email: "Thank you for the quick quote. We are still comparing three vendors, so I may need two more days before giving a final answer." What does the client imply?',
    optionA: "They have already chosen another vendor",
    optionB: "They need more time to decide",
    optionC: "They want the price reduced today",
    optionD: "They will cancel the project",
    correctAnswer: "B",
    explanation: "客戶表示仍在比較三家供應商，所以還需要幾天才會決定。",
  }),
  makeDraft({
    category: "Reading",
    subFocus: "旅遊公告細節 / Travel notice detail",
    topic: TOPIC.daily,
    difficulty: "A",
    questionText:
      'Travel notice: "Because of heavy rain, the shuttle to the airport will leave the hotel twenty minutes earlier than usual tomorrow." What should travelers do?',
    optionA: "Take the train instead of the shuttle",
    optionB: "Wait in the lobby twenty minutes later",
    optionC: "Arrive earlier than usual for the shuttle",
    optionD: "Cancel tomorrow\'s flight",
    correctAnswer: "C",
    explanation: "既然 shuttle 會提早 20 分鐘出發，旅客就要比平時更早到。",
  }),
  makeDraft({
    category: "Reading",
    subFocus: "安全公告細節 / Safety notice detail",
    topic: TOPIC.healthEnv,
    difficulty: "A",
    questionText:
      'Facility notice: "For safety reasons, used batteries should be placed in the marked recycling container near the loading dock." What are employees asked to do?',
    optionA: "Return used batteries to the front desk",
    optionB: "Store used batteries in their lockers",
    optionC: "Put used batteries in the marked recycling container",
    optionD: "Send used batteries to the supplier",
    correctAnswer: "C",
    explanation: "公告明確要求把 used batteries 放到 loading dock 附近的回收容器。",
  }),
  makeDraft({
    category: "Reading",
    subFocus: "電子郵件目的 / Email purpose",
    topic: TOPIC.office,
    difficulty: "B",
    questionText:
      'Internal e-mail: "I condensed the 18-page manual into a two-page checklist for new hires. Please tell me if any step is missing before I print copies." Why did the writer create the checklist?',
    optionA: "To replace the training manager",
    optionB: "To make the manual easier for new hires to use",
    optionC: "To announce a new printing vendor",
    optionD: "To request permission to cancel orientation",
    correctAnswer: "B",
    explanation: "作者把長手冊濃縮成 checklist，目的是讓新進員工更容易使用。",
  }),
  makeDraft({
    category: "Reading",
    subFocus: "公告推論 / Notice inference",
    topic: TOPIC.notices,
    difficulty: "B",
    questionText:
      'Announcement: "The fire drill begins at 4:20 P.M. Elevators will stop at 4:15, and all visitors must remain with their hosts." What will probably happen at 4:15 P.M.?',
    optionA: "Visitors will leave the building",
    optionB: "The elevators will no longer operate",
    optionC: "The hosts will sign out",
    optionD: "The security team will inspect badges",
    correctAnswer: "B",
    explanation: "題目已說 elevators will stop at 4:15，因此 4:15 起電梯將停止運作。",
  }),
  makeDraft({
    category: "Reading",
    subFocus: "流程推論 / Process inference",
    topic: TOPIC.meetings,
    difficulty: "B",
    questionText:
      'Meeting summary: "Mr. Wong approved the revised timeline but asked procurement to renegotiate the shipping fee. A final signature is expected after the new quote arrives." What still needs to happen before final approval?',
    optionA: "The meeting room must be changed",
    optionB: "Procurement must get a new shipping quote",
    optionC: "The legal team must rewrite the timeline",
    optionD: "The vendor must resend the invoice in print",
    correctAnswer: "B",
    explanation: "final signature 要等新的 quote 到，因此還需先拿到新的 shipping quote。",
  }),
  makeDraft({
    category: "Reading",
    subFocus: "語境字義 / Vocabulary in context",
    topic: TOPIC.coordination,
    difficulty: "B",
    questionText:
      'Message: "If the replacement parts do not arrive by noon, we will need to improvise a temporary workaround for the client demo." In this message, what does "workaround" most nearly mean?',
    optionA: "A temporary solution",
    optionB: "A long-term contract",
    optionC: "A budget reduction",
    optionD: "A travel delay",
    correctAnswer: "A",
    explanation: "workaround 在此指暫時性替代方案，而不是長期正式解法。",
  }),
  makeDraft({
    category: "Reading",
    subFocus: "語境字義 / Vocabulary in context",
    topic: TOPIC.finance,
    difficulty: "B",
    questionText:
      'Finance note: "Please flag any unusual charges before noon so we can reconcile the statement today." What does "reconcile" most nearly mean here?',
    optionA: "To apologize for a mistake",
    optionB: "To compare records and confirm they match",
    optionC: "To predict next month\'s costs",
    optionD: "To print a payment voucher",
    correctAnswer: "B",
    explanation: "reconcile the statement 指「核對帳目、確認記錄一致」。",
  }),
  makeDraft({
    category: "Reading",
    subFocus: "制度變更目的 / Process change purpose",
    topic: TOPIC.operations,
    difficulty: "B",
    questionText:
      'Operations memo: "Starting next month, regional teams will enter service data directly into the central dashboard instead of sending weekly spreadsheets. Managers will review exceptions every Friday." What is the main purpose of this change?',
    optionA: "To standardize reporting and reduce manual file handling",
    optionB: "To cancel Friday manager meetings",
    optionC: "To move all engineers to head office",
    optionD: "To lower the warranty price",
    correctAnswer: "A",
    explanation: "直接輸入 central dashboard 的目的明顯是統一資料與減少手動整理試算表。",
  }),
  makeDraft({
    category: "Reading",
    subFocus: "結果推論 / Outcome inference",
    topic: TOPIC.marketing,
    difficulty: "C",
    questionText:
      'Campaign review: "The ad received excellent click-through numbers, but most visitors left the page before viewing the product specifications. The team will revise the landing page next." What problem is suggested?',
    optionA: "The ad platform is too expensive",
    optionB: "The product itself is unavailable",
    optionC: "The landing page is not converting interested visitors",
    optionD: "The sales team forgot to send follow-up emails",
    correctAnswer: "C",
    explanation: "很多人點進來卻在看規格前離開，代表 landing page 轉換效果有問題。",
  }),
  makeDraft({
    category: "Reading",
    subFocus: "政策細節 / Policy detail",
    topic: TOPIC.logistics,
    difficulty: "C",
    questionText:
      'Policy excerpt: "Perishable items must be transferred to cold storage within thirty minutes of unloading. Any delay should be recorded and reported to the quality supervisor on the same day." What should staff do if the transfer is delayed?',
    optionA: "Discard the items immediately",
    optionB: "Record the delay and report it the same day",
    optionC: "Wait for the next weekly review meeting",
    optionD: "Send the items back to the supplier",
    correctAnswer: "B",
    explanation: "政策明確要求 delay 要記錄下來並在當天回報 quality supervisor。",
  }),
  makeDraft({
    category: "Reading",
    subFocus: "技術事故細節 / Incident detail",
    topic: TOPIC.tech,
    difficulty: "C",
    questionText:
      'Incident report: "Users could log in after the password reset, but files created between 8:10 and 8:25 were not synchronized to the backup server. IT will restore those files manually tonight." What will IT do tonight?',
    optionA: "Replace the backup server hardware",
    optionB: "Train users to change passwords",
    optionC: "Restore the unsynchronized files manually",
    optionD: "Delete the files created in the morning",
    correctAnswer: "C",
    explanation: "報告最後一句已直接說明 IT 今晚會手動還原那些未同步的檔案。",
  }),
  makeDraft({
    category: "Reading",
    subFocus: "原因推論 / Cause inference",
    topic: TOPIC.healthEnv,
    difficulty: "C",
    questionText:
      'Safety bulletin: "The air filter readings remained within the acceptable range, but two workstations showed repeated solvent odor complaints. Maintenance will inspect the ventilation valves this afternoon." Why will maintenance inspect the valves?',
    optionA: "Because the filter readings were too high",
    optionB: "Because workers reported repeated solvent odors",
    optionC: "Because a new product line is starting",
    optionD: "Because the company is closing the workshop",
    correctAnswer: "B",
    explanation: "雖然 readings 合格，但仍有異味抱怨，所以 maintenance 要檢查通風閥。",
  }),
  makeDraft({
    category: "Reading",
    subFocus: "客訴原因 / Complaint reason",
    topic: TOPIC.daily,
    difficulty: "C",
    questionText:
      'Customer complaint: "I arrived at 7:40, but the rental counter did not open until 8:15. Because I missed the first site shuttle, I had to take a taxi instead." Why is the customer probably requesting compensation?',
    optionA: "The shuttle driver was rude",
    optionB: "The rental counter opened late and caused extra travel cost",
    optionC: "The taxi fare was lower than expected",
    optionD: "The hotel canceled the reservation",
    correctAnswer: "B",
    explanation: "櫃台晚開導致客人錯過 shuttle，最後多花了 taxi 費，所以要求補償。",
  }),
  makeDraft({
    category: "Reading",
    subFocus: "寫信者意圖 / Writer intent",
    topic: TOPIC.communication,
    difficulty: "B",
    questionText:
      'Email: "I understand why the sales team wants to promise Monday delivery, but the warehouse has not confirmed available stock. Until that confirmation arrives, please avoid using firm dates with the client." What is the writer mainly trying to do?',
    optionA: "Prevent the team from promising an unconfirmed delivery date",
    optionB: "Ask the warehouse to reduce stock",
    optionC: "Move delivery to Tuesday immediately",
    optionD: "Cancel the client order",
    correctAnswer: "A",
    explanation: "寫信者主要是在阻止團隊對客戶承諾尚未確認的出貨日期。",
  }),
  makeDraft({
    category: "Reading",
    subFocus: "文件細節 / Short document detail",
    topic: TOPIC.office,
    difficulty: "A",
    questionText:
      'Checklist note: "Print the attendee labels first, then place them beside the sign-in sheet. Do not seal the welcome envelopes until the final guest count is confirmed." What should staff do after printing the attendee labels?',
    optionA: "Seal the welcome envelopes",
    optionB: "Confirm the guest count",
    optionC: "Place the labels beside the sign-in sheet",
    optionD: "Distribute the envelopes to guests",
    correctAnswer: "C",
    explanation: "流程順序很明確：先印 labels，接著把它們放在 sign-in sheet 旁邊。",
  }),
  makeDraft({
    category: "Reading",
    subFocus: "目的判斷 / Purpose",
    topic: TOPIC.notices,
    difficulty: "A",
    questionText:
      'Notice: "To reduce paper waste, monthly sales reports will no longer be printed automatically. Staff who need a hard copy should request one by Wednesday noon." What is the notice mainly about?',
    optionA: "A change in report distribution",
    optionB: "A new sales target",
    optionC: "A printer maintenance schedule",
    optionD: "A recycling event on Wednesday",
    correctAnswer: "A",
    explanation: "公告重點是 monthly sales report 的發放方式改變，不再自動列印。",
  }),
  makeDraft({
    category: "Reading",
    subFocus: "推論 / Inference",
    topic: TOPIC.meetings,
    difficulty: "A",
    questionText:
      'Planning note: "The speaker confirmed his arrival, but the interpreter has not replied yet. If we do not receive a response by noon, we will switch the session back to English only." What is the team waiting for?',
    optionA: "The final room assignment",
    optionB: "The interpreter\'s reply",
    optionC: "The speaker\'s flight number",
    optionD: "The audience survey results",
    correctAnswer: "B",
    explanation: "題目清楚表示若 noon 前收不到 interpreter 回覆，就改回英文場，因此在等 interpreter 的回覆。",
  }),
];

const drafts = [...vocabularyDrafts, ...grammarDrafts, ...readingDrafts];

export const PERSONALIZED_PHASE1_BANK: BankRow[] = drafts.map((draft) => ({
  questionText: draft.questionText,
  optionA: draft.optionA,
  optionB: draft.optionB,
  optionC: draft.optionC,
  optionD: draft.optionD,
  correctAnswer: draft.correctAnswer,
  explanation: draft.explanation,
  topic: draft.topic,
  difficulty: draft.difficulty,
  notes: formatQuestionNotes(draft.category, draft.subFocus),
  priorKnown: draft.priorKnown ?? null,
}));

export function summarizePersonalizedPhase1Bank(): Phase1BankSummary {
  const summary: Phase1BankSummary = {
    total: PERSONALIZED_PHASE1_BANK.length,
    byCategory: {
      Vocabulary: 0,
      Grammar: 0,
      Reading: 0,
    },
    byDifficulty: {
      A: 0,
      B: 0,
      C: 0,
    },
    byTopic: {},
  };

  for (const draft of drafts) {
    summary.byCategory[draft.category] += 1;
    summary.byDifficulty[draft.difficulty] += 1;
    summary.byTopic[draft.topic] = (summary.byTopic[draft.topic] ?? 0) + 1;
  }

  return summary;
}

export { TOPIC, drafts as PERSONALIZED_PHASE1_DRAFTS, makeDraft };
